<?php

    include("../../connect/conn.php");
    header("Content-type: application/json");
    $items = array();
    $rowno=0;
    $item_no = $_SESSION['item_no'];

    $sql = "select 
                  ITEM_DESC,
                  N_1,
                  N_2,
                  N_3,
                  N_4,
                  N_5,
                  N_6,
                  N_7,
                  N_8,
                  N_9,
                  N_10,
                  N_11,
                  N_12,
                  N_13,
                  N_14,
                  N_15,
                  N_16,
                  N_17,
                  N_18,
                  N_19,
                  N_20,
                  N_21,
                  N_22,
                  N_23,
                  N_24,
                  N_25,
                  N_26,
                  N_27,
                  N_28,
                  N_29,
                  N_30,
                  N_31,
                  N_32,
                  N_33,
                  N_34,
                  N_35,
                  N_36,
                  N_37,
                  N_38,
                  N_39,
                  N_40,
                  N_41,
                  N_42,
                  N_43,
                  N_44,
                  N_45,
                  N_46,
                  N_47,
                  N_48,
                  N_49,
                  N_50,
                  N_51,
                  N_52,
                  N_53,
                  N_54,
                  N_55,
                  N_56,
                  N_57,
                  N_58,
                  N_59,
                
                  N_60,
                  N_61,
                  N_62,
                  N_63,
                  N_64,
                  N_65,
                  N_66,
                  N_67,
                  N_68,
                  N_69,
                  
                  N_70,
                  N_71,
                  N_72,
                  N_73,
                  N_74,
                  N_75,
                  N_76,
                  N_77,
                  N_78,
                  N_79,
                  
                  N_80,
                  N_81,
                  N_82,
                  N_83,
                  N_84,
                  N_85,
                  N_86,
                  N_87,
                  N_88,
                  N_89,
                  
                  N_90

                   from ztb_mrp_data where item_no = $item_no and no_id in (4,5,6,7)";
    $result = oci_parse($connect, $sql);
    oci_execute($result);
    $arrData = array();
    $arrNo = 0;
    while ($row=oci_fetch_array($result)){
        $arrData[$arrNo] = array(
            "ITEM_DESC"=>rtrim($row[0]),
            "N_1"=>rtrim($row[1]),
            "N_2"=>rtrim($row[2]),
            "N_3"=>rtrim($row[3]),
            "N_4"=>rtrim($row[4]),
            "N_5"=>rtrim($row[5]),
            "N_6"=>rtrim($row[6]),
            "N_7"=>rtrim($row[8]),
            "N_8"=>rtrim($row[8]),
            "N_9"=>rtrim($row[9]),
            "N_10"=>rtrim($row[10]),
            "N_11"=>rtrim($row[11]),
            "N_12"=>rtrim($row[12]),
            "N_13"=>rtrim($row[13]),
            "N_14"=>rtrim($row[14]),
            "N_15"=>rtrim($row[15]),
            "N_16"=>rtrim($row[16]),
            "N_17"=>rtrim($row[17]),
            "N_18"=>rtrim($row[18]),
            "N_19"=>rtrim($row[19]),
            "N_20"=>rtrim($row[20]),
            "N_21"=>rtrim($row[21]),
            "N_22"=>rtrim($row[22]),
            "N_23"=>rtrim($row[23]),
            "N_24"=>rtrim($row[24]),
            "N_25"=>rtrim($row[25]),
            "N_26"=>rtrim($row[26]),
            "N_27"=>rtrim($row[27]),
            "N_28"=>rtrim($row[28]),
            "N_29"=>rtrim($row[29]),
            "N_30"=>rtrim($row[30]),
            "N_31"=>rtrim($row[31]),
            "N_32"=>rtrim($row[32]),
            "N_33"=>rtrim($row[33]),
            "N_34"=>rtrim($row[34]),
            "N_35"=>rtrim($row[35]),
            "N_36"=>rtrim($row[36]),
            "N_37"=>rtrim($row[37]),
            "N_38"=>rtrim($row[38]),
            "N_39"=>rtrim($row[39]),
            "N_40"=>rtrim($row[40]),
            "N_41"=>rtrim($row[41]),
            "N_42"=>rtrim($row[42]),
            "N_43"=>rtrim($row[43]),
            "N_44"=>rtrim($row[44]),
            "N_45"=>rtrim($row[45]),
            "N_46"=>rtrim($row[46]),
            "N_47"=>rtrim($row[47]),
            "N_48"=>rtrim($row[48]),
            "N_49"=>rtrim($row[49]),
            "N_50"=>rtrim($row[50]),
            "N_51"=>rtrim($row[51]),
            "N_52"=>rtrim($row[52]),
            "N_53"=>rtrim($row[53]),
            "N_54"=>rtrim($row[54]),
            "N_55"=>rtrim($row[55]),
            "N_56"=>rtrim($row[56]),
            "N_57"=>rtrim($row[57]),
            "N_58"=>rtrim($row[58]),
            "N_59"=>rtrim($row[59]),
            "N_60"=>rtrim($row[60]),
            "N_61"=>rtrim($row[61]),
            "N_62"=>rtrim($row[62]),
            "N_63"=>rtrim($row[63]),
            "N_64"=>rtrim($row[64]),
            "N_65"=>rtrim($row[65]),
            "N_66"=>rtrim($row[66]),
            "N_67"=>rtrim($row[67]),
            "N_68"=>rtrim($row[68]),
            "N_69"=>rtrim($row[69]),
            "N_70"=>rtrim($row[70]),
            "N_71"=>rtrim($row[71]),
            "N_72"=>rtrim($row[72]),
            "N_73"=>rtrim($row[73]),
            "N_74"=>rtrim($row[74]),
            "N_75"=>rtrim($row[75]),
            "N_76"=>rtrim($row[76]),
            "N_77"=>rtrim($row[77]),
            "N_78"=>rtrim($row[78]),
            "N_79"=>rtrim($row[79]),
            "N_70"=>rtrim($row[70]),
            "N_81"=>rtrim($row[81]),
            "N_82"=>rtrim($row[82]),
            "N_83"=>rtrim($row[83]),
            "N_84"=>rtrim($row[84]),
            "N_85"=>rtrim($row[85]),
            "N_86"=>rtrim($row[86]),
            "N_87"=>rtrim($row[87]),
            "N_88"=>rtrim($row[88]),
            "N_89"=>rtrim($row[89]),
            "N_90"=>rtrim($row[90])






        );
        $arrNo++;
    }
    echo json_encode($arrData);
?>