<?php
	session_start();
	error_reporting(0);
	set_time_limit(0);
	include("../connect/conn.php");
	$cmb_item_no = isset($_REQUEST['cmb_item_no']) ? strval($_REQUEST['cmb_item_no']) : '';

	$qry =  "select work_order,
	item_no,
	item_name,
  	cr_date,
  	qty, status, date_code,
	sum(n_1) n_1,
	sum(n_2) n_2,
	sum(n_3) n_3,
	sum(n_4) n_4,
	sum(n_5) n_5,
	sum(n_6) n_6,
	sum(n_7) n_7,
	sum(n_8) n_8,
	sum(n_9) n_9,
	sum(n_10) n_10,

	sum(n_11) n_11,
	sum(n_12) n_12,
	sum(n_13) n_13,
	sum(n_14) n_14,
	sum(n_15) n_15,
	sum(n_16) n_16,
	sum(n_17) n_17,
	sum(n_18) n_18,
	sum(n_19) n_19,
	sum(n_20) n_20,
	
	sum(n_21) n_21,
	sum(n_22) n_22,
	sum(n_23) n_23,
	sum(n_24) n_24,
	sum(n_25) n_25,
	sum(n_26) n_26,
	sum(n_27) n_27,
	sum(n_28) n_28,
	sum(n_29) n_29,
	sum(n_30) n_30,
	
	sum(n_31) n_31,
	sum(n_32) n_32,
	sum(n_33) n_33,
	sum(n_34) n_34,
	sum(n_35) n_35,
	sum(n_36) n_36,
	sum(n_37) n_37,
	sum(n_38) n_38,
	sum(n_39) n_39,
	sum(n_40) n_40,
	
	sum(n_41) n_41,
	sum(n_42) n_42,
	sum(n_43) n_43,
	sum(n_44) n_44,
	sum(n_45) n_45,
	sum(n_46) n_46,
	sum(n_47) n_47,
	sum(n_48) n_48,
	sum(n_49) n_49,
	sum(n_50) n_50,
	
	sum(n_51) n_51,
	sum(n_52) n_52,
	sum(n_53) n_53,
	sum(n_54) n_54,
	sum(n_55) n_55,
	sum(n_56) n_56,
	sum(n_57) n_57,
	sum(n_58) n_58,
	sum(n_59) n_59,
	sum(n_60) n_60,
	
	sum(n_61) n_61,
	sum(n_62) n_62,
	sum(n_63) n_63,
	sum(n_64) n_64,
	sum(n_65) n_65,
	sum(n_66) n_66,
	sum(n_67) n_67,
	sum(n_68) n_68,
	sum(n_69) n_69,
	sum(n_70) n_70,
	
	sum(n_71) n_71,
	sum(n_72) n_72,
	sum(n_73) n_73,
	sum(n_74) n_74,
	sum(n_75) n_75,
	sum(n_76) n_76,
	sum(n_77) n_77,
	sum(n_78) n_78,
	sum(n_79) n_79,
	sum(n_80) n_80,
	
	sum(n_81) n_81,
	sum(n_82) n_82,
	sum(n_83) n_83,
	sum(n_84) n_84,
	sum(n_85) n_85,
	sum(n_86) n_86,
	sum(n_87) n_87,
	sum(n_88) n_88,
	sum(n_89) n_89,
	sum(n_90) n_90
	
from 
(
   select work_order,
		  item_no,
		  item_name,
		  status,
      	  cr_date,
      	  qty, date_code, 
		  case when trim(mps_date) = trim(tgl + 1) then sum(mps_qty) else 0 end n_1,
		  case when trim(mps_date) = trim(tgl + 2) then sum(mps_qty) else 0 end n_2,
		  case when trim(mps_date) = trim(tgl + 3) then sum(mps_qty) else 0 end n_3,
		  case when trim(mps_date) = trim(tgl + 4) then sum(mps_qty) else 0 end n_4,
		  case when trim(mps_date) = trim(tgl + 5) then sum(mps_qty) else 0 end n_5,
		  case when trim(mps_date) = trim(tgl + 6) then sum(mps_qty) else 0 end n_6,
		  case when trim(mps_date) = trim(tgl + 7) then sum(mps_qty) else 0 end n_7,
		  case when trim(mps_date) = trim(tgl + 8) then sum(mps_qty) else 0 end n_8,
		  case when trim(mps_date) = trim(tgl + 9) then sum(mps_qty) else 0 end n_9,
		  case when trim(mps_date) = trim(tgl + 10) then sum(mps_qty) else 0 end n_10,
		  case when trim(mps_date) = trim(tgl + 11) then sum(mps_qty) else 0 end n_11,
		  case when trim(mps_date) = trim(tgl + 12) then sum(mps_qty) else 0 end n_12,
		  case when trim(mps_date) = trim(tgl + 13) then sum(mps_qty) else 0 end n_13,
		  case when trim(mps_date) = trim(tgl + 14) then sum(mps_qty) else 0 end n_14,
		  case when trim(mps_date) = trim(tgl + 15) then sum(mps_qty) else 0 end n_15,
		  case when trim(mps_date) = trim(tgl + 16) then sum(mps_qty) else 0 end n_16,
		  case when trim(mps_date) = trim(tgl + 17) then sum(mps_qty) else 0 end n_17,
		  case when trim(mps_date) = trim(tgl + 18) then sum(mps_qty) else 0 end n_18,
		  case when trim(mps_date) = trim(tgl + 19) then sum(mps_qty) else 0 end n_19,
		  case when trim(mps_date) = trim(tgl + 20) then sum(mps_qty) else 0 end n_20,
		  case when trim(mps_date) = trim(tgl + 21) then sum(mps_qty) else 0 end n_21,
		  case when trim(mps_date) = trim(tgl + 22) then sum(mps_qty) else 0 end n_22,
		  case when trim(mps_date) = trim(tgl + 23) then sum(mps_qty) else 0 end n_23,
		  case when trim(mps_date) = trim(tgl + 24) then sum(mps_qty) else 0 end n_24,
		  case when trim(mps_date) = trim(tgl + 25) then sum(mps_qty) else 0 end n_25,
		  case when trim(mps_date) = trim(tgl + 26) then sum(mps_qty) else 0 end n_26,
		  case when trim(mps_date) = trim(tgl + 27) then sum(mps_qty) else 0 end n_27,
		  case when trim(mps_date) = trim(tgl + 28) then sum(mps_qty) else 0 end n_28,
		  case when trim(mps_date) = trim(tgl + 29) then sum(mps_qty) else 0 end n_29,
		  case when trim(mps_date) = trim(tgl + 30) then sum(mps_qty) else 0 end n_30,
		  case when trim(mps_date) = trim(tgl + 31) then sum(mps_qty) else 0 end n_31,
		  case when trim(mps_date) = trim(tgl + 32) then sum(mps_qty) else 0 end n_32,
		  case when trim(mps_date) = trim(tgl + 33) then sum(mps_qty) else 0 end n_33,
		  case when trim(mps_date) = trim(tgl + 34) then sum(mps_qty) else 0 end n_34,
		  case when trim(mps_date) = trim(tgl + 35) then sum(mps_qty) else 0 end n_35,
		  case when trim(mps_date) = trim(tgl + 36) then sum(mps_qty) else 0 end n_36,
		  case when trim(mps_date) = trim(tgl + 37) then sum(mps_qty) else 0 end n_37,
		  case when trim(mps_date) = trim(tgl + 38) then sum(mps_qty) else 0 end n_38,
		  case when trim(mps_date) = trim(tgl + 39) then sum(mps_qty) else 0 end n_39,
		  case when trim(mps_date) = trim(tgl + 40) then sum(mps_qty) else 0 end n_40,
		  case when trim(mps_date) = trim(tgl + 41) then sum(mps_qty) else 0 end n_41,
		  case when trim(mps_date) = trim(tgl + 42) then sum(mps_qty) else 0 end n_42,
		  case when trim(mps_date) = trim(tgl + 43) then sum(mps_qty) else 0 end n_43,
		  case when trim(mps_date) = trim(tgl + 44) then sum(mps_qty) else 0 end n_44,
		  case when trim(mps_date) = trim(tgl + 45) then sum(mps_qty) else 0 end n_45,
		  case when trim(mps_date) = trim(tgl + 46) then sum(mps_qty) else 0 end n_46,
		  case when trim(mps_date) = trim(tgl + 47) then sum(mps_qty) else 0 end n_47,
		  case when trim(mps_date) = trim(tgl + 48) then sum(mps_qty) else 0 end n_48,
		  case when trim(mps_date) = trim(tgl + 49) then sum(mps_qty) else 0 end n_49,
		  case when trim(mps_date) = trim(tgl + 50) then sum(mps_qty) else 0 end n_50,
		  case when trim(mps_date) = trim(tgl + 51) then sum(mps_qty) else 0 end n_51,
		  case when trim(mps_date) = trim(tgl + 52) then sum(mps_qty) else 0 end n_52,
		  case when trim(mps_date) = trim(tgl + 53) then sum(mps_qty) else 0 end n_53,
		  case when trim(mps_date) = trim(tgl + 54) then sum(mps_qty) else 0 end n_54,
		  case when trim(mps_date) = trim(tgl + 55) then sum(mps_qty) else 0 end n_55,
		  case when trim(mps_date) = trim(tgl + 56) then sum(mps_qty) else 0 end n_56,
		  case when trim(mps_date) = trim(tgl + 57) then sum(mps_qty) else 0 end n_57,
		  case when trim(mps_date) = trim(tgl + 58) then sum(mps_qty) else 0 end n_58,
		  case when trim(mps_date) = trim(tgl + 59) then sum(mps_qty) else 0 end n_59,
		  case when trim(mps_date) = trim(tgl + 60) then sum(mps_qty) else 0 end n_60,
		  case when trim(mps_date) = trim(tgl + 61) then sum(mps_qty) else 0 end n_61,
		  case when trim(mps_date) = trim(tgl + 62) then sum(mps_qty) else 0 end n_62,
		  case when trim(mps_date) = trim(tgl + 63) then sum(mps_qty) else 0 end n_63,
		  case when trim(mps_date) = trim(tgl + 64) then sum(mps_qty) else 0 end n_64,
		  case when trim(mps_date) = trim(tgl + 65) then sum(mps_qty) else 0 end n_65,
		  case when trim(mps_date) = trim(tgl + 66) then sum(mps_qty) else 0 end n_66,
		  case when trim(mps_date) = trim(tgl + 67) then sum(mps_qty) else 0 end n_67,
		  case when trim(mps_date) = trim(tgl + 68) then sum(mps_qty) else 0 end n_68,
		  case when trim(mps_date) = trim(tgl + 69) then sum(mps_qty) else 0 end n_69,
		  case when trim(mps_date) = trim(tgl + 70) then sum(mps_qty) else 0 end n_70,
		  case when trim(mps_date) = trim(tgl + 71) then sum(mps_qty) else 0 end n_71,
		  case when trim(mps_date) = trim(tgl + 72) then sum(mps_qty) else 0 end n_72,
		  case when trim(mps_date) = trim(tgl + 73) then sum(mps_qty) else 0 end n_73,
		  case when trim(mps_date) = trim(tgl + 74) then sum(mps_qty) else 0 end n_74,
		  case when trim(mps_date) = trim(tgl + 75) then sum(mps_qty) else 0 end n_75,
		  case when trim(mps_date) = trim(tgl + 76) then sum(mps_qty) else 0 end n_76,
		  case when trim(mps_date) = trim(tgl + 77) then sum(mps_qty) else 0 end n_77,
		  case when trim(mps_date) = trim(tgl + 78) then sum(mps_qty) else 0 end n_78,
		  case when trim(mps_date) = trim(tgl + 79) then sum(mps_qty) else 0 end n_79,
		  case when trim(mps_date) = trim(tgl + 80) then sum(mps_qty) else 0 end n_80,
		  case when trim(mps_date) = trim(tgl + 81) then sum(mps_qty) else 0 end n_81,
		  case when trim(mps_date) = trim(tgl + 82) then sum(mps_qty) else 0 end n_82,
		  case when trim(mps_date) = trim(tgl + 83) then sum(mps_qty) else 0 end n_83,
		  case when trim(mps_date) = trim(tgl + 84) then sum(mps_qty) else 0 end n_84,
		  case when trim(mps_date) = trim(tgl + 85) then sum(mps_qty) else 0 end n_85,
		  case when trim(mps_date) = trim(tgl + 86) then sum(mps_qty) else 0 end n_86,
		  case when trim(mps_date) = trim(tgl + 87) then sum(mps_qty) else 0 end n_87,
		  case when trim(mps_date) = trim(tgl + 88) then sum(mps_qty) else 0 end n_88,
		  case when trim(mps_date) = trim(tgl + 89) then sum(mps_qty) else 0 end n_89,
		  case when trim(mps_date) = trim(tgl + 90) then sum(mps_qty) else 0 end n_90
   from 
   (
	 select ms.work_order,
			ms.item_no, 
			ms.item_name, 
			cast((md.mps_qty * st.quantity) / st.quantity_base as decimal(18,2))   mps_qty, 
			mps_date,
			ms.status,
			(select sysdate from dual) tgl,
      ms.cr_date, ms.qty, 
      ms.date_code
	 from 
	 structure st
	 inner join mps_header ms on ms.item_no = st.upper_item_no and st.level_no = nvl(ms.bom_level,0)
	 inner join ztb_mps_details md on md.po_no = ms.po_no and md.po_line_no = ms.po_line_no 
	 where st.lower_item_no = $cmb_item_no 
   ) group by work_order,
		  item_no,
		  item_name,
		  trim(mps_date),tgl,status,cr_date,qty,date_code
) group by work_order,
		  item_no,
		  item_name,
		  status,
      cr_date,
      qty, date_code
order by cr_date,status,item_no";
	$data_qry = oci_parse($connect, $qry);
	oci_execute($data_qry);
	$items = array();
	while ($row = oci_fetch_object($data_qry)) {
		array_push($items, $row);
		$rowno++;
	}
	$result["rows"] = $items;
	echo json_encode($result);	
?>