[
{"ID_DEPT": "C", "DEPARTEMENT": "COMPONENT DEPARTEMENT", "BUDGET": "0", "CURRENCY": ""},
{"ID_DEPT": "A", "DEPARTEMENT": "ASSEMBLING DEPARTEMENT", "BUDGET": "0", "CURRENCY": ""},
{"ID_DEPT": "F", "DEPARTEMENT": "FINISHING DEPARTEMENT", "BUDGET": "0", "CURRENCY": ""},
{"ID_DEPT": "Q", "DEPARTEMENT": "QUALITY DEPARTEMENT", "BUDGET": "0", "CURRENCY": ""},
{"ID_DEPT": "P", "DEPARTEMENT": "PE", "BUDGET": "0", "CURRENCY": ""},
{"ID_DEPT": "S", "DEPARTEMENT": "SCM", "BUDGET": "0", "CURRENCY": ""},
{"ID_DEPT": "G", "DEPARTEMENT": "GA", "BUDGET": "0", "CURRENCY": ""},
{"ID-DEPT": "W", "DEPARTEMENT": "WAREHOUSE", "CURRENCY": ""}
]