<?php
	session_start();
	error_reporting(0);
	set_time_limit(0);
	include("../../../connect/conn.php");
	$cmb_item_no = isset($_REQUEST['cmb_item_no']) ? strval($_REQUEST['cmb_item_no']) : '';

	$qry =  "select work_order,
	item_no,
	item_name,
  	CAST(cr_date as varchar) as cr_date,
  	qty, status, date_code,
	ceiling(sum(n_1)) n_1,
	ceiling(sum(n_2)) n_2,
	ceiling(sum(n_3)) n_3,
	ceiling(sum(n_4)) n_4,
	ceiling(sum(n_5)) n_5,
	ceiling(sum(n_6)) n_6,
	ceiling(sum(n_7)) n_7,
	ceiling(sum(n_8)) n_8,
	ceiling(sum(n_9)) n_9,
	ceiling(sum(n_10)) n_10,

	ceiling(sum(n_11)) n_11,
	ceiling(sum(n_12)) n_12,
	ceiling(sum(n_13)) n_13,
	ceiling(sum(n_14)) n_14,
	ceiling(sum(n_15)) n_15,
	ceiling(sum(n_16)) n_16,
	ceiling(sum(n_17)) n_17,
	ceiling(sum(n_18)) n_18,
	ceiling(sum(n_19)) n_19,
	ceiling(sum(n_20)) n_20,
	
	ceiling(sum(n_21)) n_21,
	ceiling(sum(n_22)) n_22,
	ceiling(sum(n_23)) n_23,
	ceiling(sum(n_24)) n_24,
	ceiling(sum(n_25)) n_25,
	ceiling(sum(n_26)) n_26,
	ceiling(sum(n_27)) n_27,
	ceiling(sum(n_28)) n_28,
	ceiling(sum(n_29)) n_29,
	ceiling(sum(n_30)) n_30,
	
	ceiling(sum(n_31)) n_31,
	ceiling(sum(n_32)) n_32,
	ceiling(sum(n_33)) n_33,
	ceiling(sum(n_34)) n_34,
	ceiling(sum(n_35)) n_35,
	ceiling(sum(n_36)) n_36,
	ceiling(sum(n_37)) n_37,
	ceiling(sum(n_38)) n_38,
	ceiling(sum(n_39)) n_39,
	ceiling(sum(n_40)) n_40,
	
	ceiling(sum(n_41)) n_41,
	ceiling(sum(n_42)) n_42,
	ceiling(sum(n_43)) n_43,
	ceiling(sum(n_44)) n_44,
	ceiling(sum(n_45)) n_45,
	ceiling(sum(n_46)) n_46,
	ceiling(sum(n_47)) n_47,
	ceiling(sum(n_48)) n_48,
	ceiling(sum(n_49)) n_49,
	ceiling(sum(n_50)) n_50,
	
	ceiling(sum(n_51)) n_51,
	ceiling(sum(n_52)) n_52,
	ceiling(sum(n_53)) n_53,
	ceiling(sum(n_54)) n_54,
	ceiling(sum(n_55)) n_55,
	ceiling(sum(n_56)) n_56,
	ceiling(sum(n_57)) n_57,
	ceiling(sum(n_58)) n_58,
	ceiling(sum(n_59)) n_59,
	ceiling(sum(n_60)) n_60,
	
	ceiling(sum(n_61)) n_61,
	ceiling(sum(n_62)) n_62,
	ceiling(sum(n_63)) n_63,
	ceiling(sum(n_64)) n_64,
	ceiling(sum(n_65)) n_65,
	ceiling(sum(n_66)) n_66,
	ceiling(sum(n_67)) n_67,
	ceiling(sum(n_68)) n_68,
	ceiling(sum(n_69)) n_69,
	ceiling(sum(n_70)) n_70,
	
	ceiling(sum(n_71)) n_71,
	ceiling(sum(n_72)) n_72,
	ceiling(sum(n_73)) n_73,
	ceiling(sum(n_74)) n_74,
	ceiling(sum(n_75)) n_75,
	ceiling(sum(n_76)) n_76,
	ceiling(sum(n_77)) n_77,
	ceiling(sum(n_78)) n_78,
	ceiling(sum(n_79)) n_79,
	ceiling(sum(n_80)) n_80,
	
	ceiling(sum(n_81)) n_81,
	ceiling(sum(n_82)) n_82,
	ceiling(sum(n_83)) n_83,
	ceiling(sum(n_84)) n_84,
	ceiling(sum(n_85)) n_85,
	ceiling(sum(n_86)) n_86,
	ceiling(sum(n_87)) n_87,
	ceiling(sum(n_88)) n_88,
	ceiling(sum(n_89)) n_89,
	ceiling(sum(n_90)) n_90
	
from 
(
   select work_order,
		  item_no,
		  item_name,
		  [status],
      	  cr_date,
      	  qty, date_code, 
		  case when mps_date = CONVERT(varchar(10),dateadd(day,1,tgl),120) then sum(mps_qty) else 0 end n_1,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,2,tgl),120) then sum(mps_qty) else 0 end n_2,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,3,tgl),120) then sum(mps_qty) else 0 end n_3,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,4,tgl),120) then sum(mps_qty) else 0 end n_4,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,5,tgl),120) then sum(mps_qty) else 0 end n_5,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,6,tgl),120) then sum(mps_qty) else 0 end n_6,   
		  case when mps_date = CONVERT(varchar(10),dateadd(day,7,tgl),120) then sum(mps_qty) else 0 end n_7,  
		  case when mps_date = CONVERT(varchar(10),dateadd(day,8,tgl),120) then sum(mps_qty) else 0 end n_8,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,9,tgl),120) then sum(mps_qty) else 0 end n_9,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,10,tgl),120) then sum(mps_qty) else 0 end n_10,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,11,tgl),120) then sum(mps_qty) else 0 end n_11,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,12,tgl),120) then sum(mps_qty) else 0 end n_12,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,13,tgl),120) then sum(mps_qty) else 0 end n_13,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,14,tgl),120) then sum(mps_qty) else 0 end n_14,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,15,tgl),120) then sum(mps_qty) else 0 end n_15,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,16,tgl),120) then sum(mps_qty) else 0 end n_16,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,17,tgl),120) then sum(mps_qty) else 0 end n_17,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,18,tgl),120) then sum(mps_qty) else 0 end n_18,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,19,tgl),120) then sum(mps_qty) else 0 end n_19,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,20,tgl),120) then sum(mps_qty) else 0 end n_20,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,21,tgl),120) then sum(mps_qty) else 0 end n_21,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,22,tgl),120) then sum(mps_qty) else 0 end n_22,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,23,tgl),120) then sum(mps_qty) else 0 end n_23,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,24,tgl),120) then sum(mps_qty) else 0 end n_24,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,25,tgl),120) then sum(mps_qty) else 0 end n_25,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,26,tgl),120) then sum(mps_qty) else 0 end n_26,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,27,tgl),120) then sum(mps_qty) else 0 end n_27,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,28,tgl),120) then sum(mps_qty) else 0 end n_28,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,29,tgl),120) then sum(mps_qty) else 0 end n_29,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,30,tgl),120) then sum(mps_qty) else 0 end n_30,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,31,tgl),120) then sum(mps_qty) else 0 end n_31,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,32,tgl),120) then sum(mps_qty) else 0 end n_32,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,33,tgl),120) then sum(mps_qty) else 0 end n_33,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,34,tgl),120) then sum(mps_qty) else 0 end n_34,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,35,tgl),120) then sum(mps_qty) else 0 end n_35,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,36,tgl),120) then sum(mps_qty) else 0 end n_36,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,37,tgl),120) then sum(mps_qty) else 0 end n_37,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,38,tgl),120) then sum(mps_qty) else 0 end n_38,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,39,tgl),120) then sum(mps_qty) else 0 end n_39,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,40,tgl),120) then sum(mps_qty) else 0 end n_40,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,41,tgl),120) then sum(mps_qty) else 0 end n_41,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,42,tgl),120) then sum(mps_qty) else 0 end n_42,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,43,tgl),120) then sum(mps_qty) else 0 end n_43,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,44,tgl),120) then sum(mps_qty) else 0 end n_44,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,45,tgl),120) then sum(mps_qty) else 0 end n_45,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,46,tgl),120) then sum(mps_qty) else 0 end n_46,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,47,tgl),120) then sum(mps_qty) else 0 end n_47,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,48,tgl),120) then sum(mps_qty) else 0 end n_48,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,49,tgl),120) then sum(mps_qty) else 0 end n_49,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,50,tgl),120) then sum(mps_qty) else 0 end n_50,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,51,tgl),120) then sum(mps_qty) else 0 end n_51,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,52,tgl),120) then sum(mps_qty) else 0 end n_52,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,53,tgl),120) then sum(mps_qty) else 0 end n_53,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,54,tgl),120) then sum(mps_qty) else 0 end n_54,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,55,tgl),120) then sum(mps_qty) else 0 end n_55,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,56,tgl),120) then sum(mps_qty) else 0 end n_56,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,57,tgl),120) then sum(mps_qty) else 0 end n_57,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,58,tgl),120) then sum(mps_qty) else 0 end n_58,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,59,tgl),120) then sum(mps_qty) else 0 end n_59,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,60,tgl),120) then sum(mps_qty) else 0 end n_60,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,61,tgl),120) then sum(mps_qty) else 0 end n_61,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,62,tgl),120) then sum(mps_qty) else 0 end n_62,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,63,tgl),120) then sum(mps_qty) else 0 end n_63,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,64,tgl),120) then sum(mps_qty) else 0 end n_64,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,65,tgl),120) then sum(mps_qty) else 0 end n_65,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,66,tgl),120) then sum(mps_qty) else 0 end n_66,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,67,tgl),120) then sum(mps_qty) else 0 end n_67,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,68,tgl),120) then sum(mps_qty) else 0 end n_68,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,69,tgl),120) then sum(mps_qty) else 0 end n_69,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,70,tgl),120) then sum(mps_qty) else 0 end n_70,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,71,tgl),120) then sum(mps_qty) else 0 end n_71,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,72,tgl),120) then sum(mps_qty) else 0 end n_72,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,73,tgl),120) then sum(mps_qty) else 0 end n_73,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,74,tgl),120) then sum(mps_qty) else 0 end n_74,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,75,tgl),120) then sum(mps_qty) else 0 end n_75,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,76,tgl),120) then sum(mps_qty) else 0 end n_76,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,77,tgl),120) then sum(mps_qty) else 0 end n_77,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,78,tgl),120) then sum(mps_qty) else 0 end n_78,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,79,tgl),120) then sum(mps_qty) else 0 end n_79,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,80,tgl),120) then sum(mps_qty) else 0 end n_80,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,81,tgl),120) then sum(mps_qty) else 0 end n_81,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,82,tgl),120) then sum(mps_qty) else 0 end n_82,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,83,tgl),120) then sum(mps_qty) else 0 end n_83,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,84,tgl),120) then sum(mps_qty) else 0 end n_84,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,85,tgl),120) then sum(mps_qty) else 0 end n_85,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,86,tgl),120) then sum(mps_qty) else 0 end n_86,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,87,tgl),120) then sum(mps_qty) else 0 end n_87,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,88,tgl),120) then sum(mps_qty) else 0 end n_88,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,89,tgl),120) then sum(mps_qty) else 0 end n_89,
		  case when mps_date = CONVERT(varchar(10),dateadd(day,90,tgl),120) then sum(mps_qty) else 0 end n_90
   from 
   (
	 select ms.work_order,
			ms.item_no, 
			ms.item_name, 
			cast((md.mps_qty * st.quantity) / st.quantity_base as decimal(18,2))   mps_qty, 
			mps_date,
			ms.status,
			CONVERT(varchar(10),getdate(), 120) tgl,
      ms.cr_date, ms.qty, 
      ms.date_code
	 from 
	 structure st
	 inner join mps_header ms on ms.item_no = st.upper_item_no and st.level_no = isnull(ms.bom_level,0)
	 inner join ztb_mps_details md on md.po_no = ms.po_no and md.po_line_no = ms.po_line_no 
	 where st.lower_item_no = $cmb_item_no 
   )ss group by work_order,
		  item_no,
		  item_name,
		  mps_date,tgl,status,cr_date,qty,date_code
)bb group by work_order,
		  item_no,
		  item_name,
		  status,
      cr_date,
      qty, date_code
order by cr_date,status,item_no";

	// echo $qry.'<br/>';
	$data_qry = sqlsrv_query($connect, strtoupper($qry));
	$items = array();
	while ($row = sqlsrv_fetch_object($data_qry)) {
		array_push($items, $row);
		$rowno++;
	}
	$result["rows"] = $items;
	echo json_encode($result);	
?>