[
{"idgrp": "D-S", "nmgrp": "D-S : DIRECT"},
{"idgrp": "I-C" , "nmgrp": "I-C : KODE IC"},
{"idgrp": "I-DIR", "nmgrp": "I-DIR : DIRECT SPARE PART"},
{"idgrp": "I-E", "nmgrp": "I-E : KODE IE"},
{"idgrp": "I-G" , "nmgrp": "I-G : KODE IG"},
{"idgrp": "I-W" , "nmgrp": "I-W : KODE IW"},
{"idgrp": "I-Y" , "nmgrp": "I-Y : KODE IY"},
{"idgrp": "I-Z" , "nmgrp": "I-Z : KODE IZ"},
{"idgrp": "L-A" , "nmgrp": "L-A : KODE A"},
{"idgrp": "L-B" , "nmgrp": "L-B : KODE B"},
{"idgrp": "L-C" , "nmgrp": "L-C : KODE C"},
{"idgrp": "L-D" , "nmgrp": "L-D : KODE D"},
{"idgrp": "L-DIR", "nmgrp": "L-DIR : DIRECT SPARE PART"},
{"idgrp": "L-E" , "nmgrp": "L-E : KODE E"},
{"idgrp": "L-F" , "nmgrp": "L-F : KODE F"},
{"idgrp": "L-G" , "nmgrp": "L-G : KODE G"},
{"idgrp": "L-H" , "nmgrp": "L-H : KODE H"},
{"idgrp": "L-I" , "nmgrp": "L-I : KODE I"},
{"idgrp": "L-J" , "nmgrp": "L-J : KODE J"},
{"idgrp": "L-W" , "nmgrp": "L-W : KODE W"},
{"idgrp": "L-X" , "nmgrp": "L-X : KODE X"},
{"idgrp": "L-Y" , "nmgrp": "L-Y : KODE Y"},
{"idgrp": "L-Z" , "nmgrp": "L-Z : KODE Z"},
{"idgrp": "S-C" , "nmgrp": "S-C : KODE SC"},
{"idgrp": "S-D" , "nmgrp": "S-D : DIRECT COMMON"}
]